[package]
name = "ffi"
version = "0.1.0"
authors = ["David Cowden <david@uno.app>"]
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
uno = { path = "../lib" }

[build-dependencies]
cbindgen = "0.20"
