binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
enum_discrim_align_threshold = 0
fn_args_layout = "Tall"
fn_single_line = true
format_strings = true
group_imports = "Preserve"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
indent_style = "Block"
license_template_path = ".rustfmt.license-template"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
report_todo = "Never"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false 
struct_field_align_threshold = 0
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_small_heuristics = "Max"
version = "Two"
wrap_comments = true
