[package]
name = "xcf"
version = "0.1.0"
authors = ["David Cowden <david@withuno.com>"]
license = "AGPL-3.0-only"
edition = "2018"

[lib]
name = "unoxcf"
crate-type = ["staticlib"]

[dependencies]
ffi = { path = "../ffi" }

[build-dependencies]
cbindgen = "0.20"
